# Normalized configuration for Vocal Smart Splitter (v2.x)
# Focus: Pure vocal detection with BPM/MDD/VPP adaptation and weighted NMS

audio:
  sample_rate: 44100
  channels: 1
  format: wav
  quality: 320

gpu_pipeline:
  enable: false
  prefer_device: cuda
  chunk_seconds: 10.0
  overlap_seconds: 2.5
  halo_seconds: 0.5
  prefetch_pinned_buffers: 2
  inflight_chunks_limit: 2

pure_vocal_detection:
  enable: true
  # Base detection
  min_pause_duration: 0.5
  breath_duration_range: [0.1, 0.3]
  f0_weight: 0.30
  formant_weight: 0.25
  spectral_weight: 0.25
  duration_weight: 0.20

  # Relative energy valleys (robust defaults)
  enable_relative_energy_mode: true
  peak_relative_threshold_ratio: 0.22   # recommended 0.16–0.22
  rms_relative_threshold_ratio: 0.26    # recommended 0.20–0.26

  # BPM/MDD-driven adaptation of relative thresholds
  relative_threshold_adaptation:
    enable: true
    clamp_min: 0.75
    clamp_max: 1.25
    bpm:
      slow_multiplier: 1.10
      medium_multiplier: 1.00
      fast_multiplier: 0.85
    mdd:
      base: 1.0
      gain: 0.2

  # VPP (Vocal Pause Profile) adaptation — only within singing blocks; exclude interludes
  pause_stats_adaptation:
    enable: true
    delta_db: 3.0               # voice_active = floor_db + delta_db
    morph_close_ms: 150         # close then open (run-length morphology)
    morph_open_ms: 50
    sing_block_min_s: 2.0
    interlude_min_s: 4.0
    interlude_coverage_check:
      enable: false             # optional: only drop long rests if ±pad coverage < threshold
      pad_seconds: 2.0          # ±padding window for coverage measurement
      coverage_threshold: 0.10  # voice_active coverage threshold within padded window
    classify_thresholds:
      slow: { mpd: 0.60, p95: 1.20, rr: 0.35 }
      fast: { mpd: 0.25, pr: 18, rr: 0.15 }
    multipliers: { slow: 1.10, medium: 1.00, fast: 0.85 }
    clamp_min: 0.75
    clamp_max: 1.25

  # Candidate scoring and NMS preferences
  valley_scoring:
    w_len: 0.9
    w_quiet: 0.8
    w_flat: 0.1
    use_weighted_nms: true
    merge_close_ms: 80            # 合并间隔≤此阈值的小停顿（默认80ms）
    max_raw_candidates: 1200      # 能量谷原始候选上限，防爆炸
    max_kept_after_nms: 150       # NMS后最多保留的切点数，避免后续计算爆炸

spectral_classifier:
  breath_threshold: 0.3
  pause_threshold: 0.7
  uncertain_range: [0.3, 0.7]
  f0_weight: 0.25
  formant_weight: 0.20
  spectral_weight: 0.20
  duration_weight: 0.20
  energy_weight: 0.15

musical_dynamic_density:
  enable: true
  energy_weight: 0.5
  spectral_weight: 0.3
  onset_weight: 0.2
  threshold_multiplier: 0.2
  max_multiplier: 1.4
  min_multiplier: 0.6
  chorus_detection:
    enable: true
    energy_threshold: 0.55
    density_threshold: 0.75
    multiplier: 1.1
  segment_analysis:
    window_overlap: 0.5
    smoothing_factor: 0.3
    min_segment_duration: 8.0

quality_control:
  validate_split_points: true
  # adaptive (may be overridden by BPM layer if present)
  min_pause_at_split: 1.0
  min_split_gap: 1.2
  # static constraints
  min_vocal_content_ratio: 0.4
  max_silence_ratio: 0.3
  enable_zero_crossing_align: true
  fade_in_duration: 0.0
  fade_out_duration: 0.0
  normalize_audio: false
  remove_click_noise: false
  smooth_transitions: false
  # Length governance (V2 finalize)
  segment_min_duration: 6.0
  segment_max_duration: 18.0
  # Quiet guard override (optional)
  enforce_quiet_cut:
    win_ms: 80
    guard_db: 2.5
    search_right_ms: 200
    floor_percentile: 5

smart_splitting:
  use_pause_priority_algorithm: false
  use_precise_voice_algorithm: false
  min_segment_length: 4
  max_segment_length: 18
  target_segment_length: 8

vocal_separation:
  hpss_margin: 2.0
  hpss_power: 1.5
  mask_threshold: 0.2
  mask_smoothing: 1
  vocal_freq_min: 100
  vocal_freq_max: 4000
  vocal_core_min: 200
  vocal_core_max: 1000
  min_vocal_ratio: 0.15
  max_noise_ratio: 0.3

breath_detection:
  energy_window: 0.04
  energy_hop: 0.005
  energy_threshold: 0.018
  spectral_window: 0.08
  spectral_threshold: 0.2
  min_pause_duration: 0.8
  max_pause_duration: 3.0
  pause_merge_threshold: 0.06
  breath_energy_drop: 0.6
  breath_duration_min: 0.8
  breath_duration_max: 1.2

content_analysis:
  min_vocal_segment: 3.0
  max_vocal_segment: 30.0
  continuity_threshold: 0.5
  semantic_gap_max: 1.0
  vocal_clarity_min: 0.6
  content_completeness: 0.8

output:
  directory: './output'
  naming_pattern: 'segment_{index:03d}'
  include_metadata: true
  save_debug_info: true
  save_separated_vocal: false
  save_breath_map: false
  save_analysis_report: true

logging:
  level: 'INFO'
  file: 'smart_splitter.log'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_file_size: '10MB'
  backup_count: 3
